name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
    - uses: actions/checkout@v2
    - name: CI
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pnpm install
    - run: npm run lint
    - run: npm run build
    - run: npm run test
      env:
        CI: true
